# This is a scheduled workflow

name: Scheduled Workflow

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command
        run: echo "This is a scheduled job running every 30 minutes!"