name: Scheduled Cupra Tibber Sync

on:
  schedule:
    - cron: '0 * * * *' # every hour
  push:
    paths:
      - main.sh
      - .github/workflows/scheduled.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
      TIBBER_EMAIL: ${{ secrets.TIBBER_EMAIL }}
      TIBBER_PASSWORD: ${{ secrets.TIBBER_PASSWORD }}
      VIN: ${{ secrets.VIN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run sync script
        run: bash main.sh