name: Scheduled Cupra Tibber Sync

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
    steps:
      - uses: actions/checkout@v4
      - name: Run sync script
        run: bash main.sh